<?php

/**
 * Implements hook_theme
 */
function s2e_panels_theme() {
  return array(

  );
}

function s2e_panels_video() {
  global $language;
  $query = new EntityFieldQuery();
  $result = $query->entityCondition('entity_type', 'node')
    ->propertyCondition('status', 1)
    ->propertyCondition('promote', 1)
    ->propertyCondition('type', 'video_screencast')
    ->propertyCondition('language', $language->language)
    ->propertyOrderBy('created', 'DESC')
    ->pager(2)
    ->execute();
  $nodes = node_load_multiple(array_keys($result['node']));
  //
  $output = array();
  foreach ($nodes as $nid => $node) {
    $thumb_uri = $node->field_pagefront_image[LANGUAGE_NONE][0]['uri'];
    $thumb = theme_image_style(array(
      'style_name' => 'pagefront_image',
      'path' => $thumb_uri,
      'alt' => check_plain($node->title),
      'width' => 220,
      'height' => 220,
    ));
    $output[] = '<li class="info-block ' . $node->type . '" id="node_' . $node->nid . '">' . $thumb . '</li>';
  }
  return implode("\n", $output);
}

function s2e_panels_page() {
  $path = path_to_theme() . '/img/menu/';
  $output = array(
    '<li id="cost" class="info-block last">' . theme('image', array(
      'path' => $path . 'cost_services.gif',
      'alt' => t('Cost of services')
    )) . '</li>',
    '<li id="faq" class="info-block">' . theme('image', array(
      'path' => $path . 'faq.gif',
      'alt' => t('F.A.Q.')
    )) . '</li>',
    '<li id="support" class="info-block">' . theme('image', array(
      'path' => $path . 'supp_contacts.gif',
      'alt' => t('Support')
    )) . '</li>',
    '<li id="events" class="info-block last">' . theme('image', array(
      'path' => $path . 'events.gif',
      'alt' => t('Events')
    )) . '</li>',
  );
  //
  return implode("\n", $output);
}

function s2e_panels_login() {
  $login_form = drupal_get_form('s2e_user_login_block');
  $output = theme('image', array(
    'path' => path_to_theme() . '/img/menu/ent_reg.gif',
    'alt' => 'Вход/Регистрация',
    'attributes' => array('id' => 'ent-reg-ico')
  ));
  $output .= '<div id="entrance">' . render($login_form) . '</div>';
  $output .= '<div id="ent-reg-line"></div>';
  $output .= '<div id="registration">' . theme('image', array('path' => path_to_theme() . '/img/menu/reg-men.png')) . '<br/>' . l(t('Registration'), 'user/register') . '</div>';
  //
  $output = '<li id="ent-reg" class="last">' . $output . '</li>';
  return $output;
}

function s2e_user_login_block($form) {
  //$form['#action'] = url(current_path(), array('query' => drupal_get_destination(), 'external' => FALSE));
  $form['#id'] = 'user-login-form';
  $form['#validate'] = user_login_default_validators();
  $form['#submit'][] = 'user_login_submit';
  $form['name'] = array(
    '#type' => 'textfield',
    '#maxlength' => USERNAME_MAX_LENGTH,
    '#size' => 15,
    '#value' => 'Логин (адрес элестронной почты)',
  );
  $form['pass'] = array(
    '#type' => 'password',
    '#maxlength' => 60,
    '#size' => 15,
    '#value' => 'Пароль',
  );
  $form['remember'] = array(
    '#markup' => l('Забыли пароль?', 'user/password', array('attributes' => array('id' => 'remember')))
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Log in'),
    '#attributes' => array(
      'class' => array('btn'),
    )
  );
  //
  return $form;
}

//ToDo - переделать на динамическую генерацию из ноды
function s2e_panels_banner() {
  $path = path_to_theme() . '/img/menu/';
  $mark_image_path = $path . 'mark_1.gif';
  $output[] = '
  <li class="royalSlide" data-thumb="' . $mark_image_path . '">
    ' . theme('image', array('path' => $path . 'slider/img_1.jpg', 'width' => 448, 'height' => 220)) . '
    <div class="royalCaption">
      <div class="royalCaptionItem" data-show-effect="fade movetop" data-move-offset="15" style="margin: 15px 0 0 15px; text-transform: uppercase; width: 400px; color: #484846; font: bold 24px Arial">The best inspiration.</div>
      <h2 class="royalCaptionItem" data-show-effect="fade moveleft" style="margin: 40px 0 0 25px; width: 300px; color: #525252; font: bold 17px Arial">MOSCOW, Aug 1st</h2>
    </div>
  </li>';
  $output[] = '
  <li class="royalSlide" data-thumb="' . $mark_image_path . '">
    ' . theme('image', array('path' => $path . 'slider/img_2.jpg', 'width' => 448, 'height' => 220)) . '
    <div class="royalCaption">
      <div class="royalCaptionItem" data-move-offset="15" style="margin: 15px 0 0 210px; width: 400px; color: #fff; font: 20px Arial">Marketing in Russia/CIS</div>
      <h2 class="royalCaptionItem" data-show-effect="fade moveleft" style="margin: 38px 0 0 255px; width: 400px; color: #fff; font: 15px Arial">Cisco Expo Moscow 2011</h2>
    </div>
  </li>';
  //
  return implode("\n", $output);
}